callback({
	"character":{
		"userName":"豆腐2333",
		"guanZhu":25,
		"fenShi":33,
		"qianMing":"有能力的时候，便应该为将来未雨绸缪"
	},
	"dajiataolu":[
		{
			"shuoMing":"#10年投资翻6倍药不能食停#",
			"name":"基金经理访谈",
			"imgURl":"img/ dajiaotaolun (1).jpg"
		},
		{
			"shuoMing":"#我的理财心得#",
			"name":"基金公司活动",
			"imgUrl":"img/ dajiaotaolun (2).jpg"
		}
	],
	"taolunrenshu":[
		{
			"name":"定期理财",
			"personNum":"4万评论"
		},
		{
			"name":"存金宝",
			"personNum":"50万评论"},
		{
			"name":"基金综合",
			"personNum":"8万评论"},
			
		{
			"name":"聚宝官方",
			"personNum":"1741评论"
		}
	],
	"dongtai":[
		{
			"activeType":"优选",
			"name":"万家基金莫海波",
			"time":"6小时前",
			"title":"三季度我们买了什么股票?",
			"jieshao":"近期我们基金的三季报对外发布，很多聚宝的同学们非常关注，下面转发一篇媒体(牛熊交易...(n",
			"imgURl":"img/-camera.jpg",
			"imgCont":"5",
			"xiaoxi":"5",
			"dianzan":"4"
		},
		{
			"activeType":"优选",
			"name":"广发基金",
			"time":"20小时前",
			"title":"传说，定投的江湖里流传着两大奥义...",
			"jieshao":"传说，定投的江湖里流传着两大奥义...",
			"imgURl":"img/-camera.jpg",
			"imgCont":"5",
			"xiaoxi":"16",
			"dianzan":"4"
		},
		{
			"activeType":"猜你喜欢",
			"name":"策鸡司令",
			"time":"8小时前",
			"title":"",
			"jieshao":"我带领军团兄弟国庆前期退出存金宝避免大跌，国庆结束又在272杀入存金宝当时就放言存金宝能涨到285左右！白银赚5个点位即可...",
			"imgURl":"",
			"imgCont":"5",
			"xiaoxi":"206",
			"dianzan":"99"
		},
		{
			"activeType":"猜你喜欢",
			"name":"金石为涨",
			"time":"11-04 11：44",
			"title":"",
			"jieshao":"存金宝283.50在昨天晚上跌的比较厉害的时候有个朋友私信跟我说，他在292买入的八万存宝宝.问还能不能涨回来！我回答大涨回来肯定...",
			"imgURl":"",
			"imgCont":"5",
			"xiaoxi":"175",
			"dianzan":"109"
		},
		{
			"activeType":"猜你喜欢",
			"name":"龙行天下虎",
			"time":"11-04 09:30",
			"title":"",
			"jieshao":"昨天白天下跌肯定吓到你们了，晚上小非农数据利多迅速从281爬升到今天284.19有望在通过今晚美国大非农数据冲击288，今晚八点...数",
			"imgURl":"img/-camera.jpg",
			"imgCont":"5",
			"xiaoxi":"5",
			"dianzan":"4"
		},
		{
			"activeType":"大家都在看",
			"name":"中书省",
			"time":"11-04 12:30",
			"title":"",
			"jieshao":"又到周五了，很多人都戏称今天是”黑色星期五“。从黄金的规则可以看的话可以这样说。国庆那段时间黄金就出现了断崖式下跌，很多人认...",
			"imgURl":"",
			"imgCont":"5",
			"xiaoxi":"65",
			"dianzan":"18"
		},
		{
			"activeType":"猜你喜欢",
			"name":"博时黄金资讯",
			"time":"11-03 17:00",
			"title":"#叽歪黄金#美国大选之后还能不能现金？",
			"jieshao":"距离美国大选还有5天，最新消息显示，川普民选票数已反超希啦里，看到邮件门对希拉里打击不...",
			"imgURl":"",
			"imgCont":"5",
			"xiaoxi":"5",
			"dianzan":"4"
		},
		{
			"activeType":"优选",
			"name":"万家基金莫海波",
			"time":"6小时前",
			"title":"三季度我们买了什么股票?",
			"jieshao":"近期我们基金的三季报对外发布，很多聚宝的同学们非常关注，下面转发一篇媒体(牛熊交易...(n",
			"imgURl":"dongtai_img",
			"imgCont":"5",
			"xiaoxi":"5",
			"dianzan":"4"
		}
	],
	"discover":[
		{
			"title":"名人堂",
			"person":[
				{
					"name":"财经美女抱",
					"jieshan":"千语文化，一个有想法的团队，不...",
					"zan_guanzhu":"被1293人关注，最近收到66个赞",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"天弘刘冬",
					"jieshan":"关注：4 粉丝：292万",
					"zan_guanzhu":"被2921448人关注，最近收到83个赞",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"新钱NewMoney",
					"jieshan":"上海珠玑文化信息技术有限公司，是...",
					"zan_guanzhu":"被6797人关注，最近收到285个赞",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"民生加银基金",
					"jieshan":"关注：3 粉丝：9416",
					"zan_guanzhu":"被5683人关注，最近收到130个赞",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"博时黄金资讯",
					"jieshan":"用专业捕捉资讯，用观点解读金市",
					"zan_guanzhu":"被2317人关注，最近收到65个赞",
					"imageURl":"img/-camera.jpg"
				}
			]
		},
		{
			"title":"特别推荐",
			"person":[
				{
					"name":"赚是硬道理",
					"jieshan":"每交易日下年2：30操作建议，不改名...",
					"zan_guanzhu":"最近收到2528个赞",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"吉吉啊哥",
					"jieshan":"听课：wx471330002",
					"zan_guanzhu":"最近收到977个赞",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"轩辕建安",
					"jieshan":"一直在强调，我不是大神。我写的文..",
					"zan_guanzhu":"最近收到941个赞",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"玩转基市",
					"jieshan":"行情总在绝望中诞生，半信半疑中成...",
					"zan_guanzhu":"最近收到175个赞",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"中书省",
					"jieshan":"大家庭5516925...",
					"zan_guanzhu":"最近收到171个赞",
					"imageURl":"img/-camera.jpg"
				}
			]
		},
		{
			"title":"收益高手",
			"person":[
				{
					"name":"无忧wy",
					"jieshan":"关注：8 粉丝：1534",
					"zan_guanzhu":"收益率超过99%同行的达人",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"牛鑫斌",
					"jieshan":"关注：1 粉丝：197",
					"zan_guanzhu":"收益率超过99%同行的达人",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"秒天里的一坨屎",
					"jieshan":"养鸡，追求稳健兼顾收益",
					"zan_guanzhu":"收益率超过99%同行的达人",
					"imageURl":"img/-camera.jpg"
				}
			]
		},
		{
			"title":"优质TOP3",
			"person":[
				{
					"name":"jing55446688",
					"jieshan":"想加我扫头像",
					"zan_guanzhu":"本期提问积分：1830",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"亲二爷",
					"jieshan":"三段客",
					"zan_guanzhu":"本期提问积分：1368",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"喵儿菇凉",
					"jieshan":"关注：8 粉丝：2233",
					"zan_guanzhu":"本期提问积分：1061",
					"imageURl":"img/-camera.jpg"
				}
			]
		},
		{
			"title":"博学答题TOP3",
			"person":[
				{
					"name":"文学和理财",
					"jieshan":"喜欢文学和理财",
					"zan_guanzhu":"本期回答积分：1723",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"王王王005",
					"jieshan":"关注：17 粉丝：7378",
					"zan_guanzhu":"本期回答积分：1157",
					"imageURl":"img/-camera.jpg"
				},
				{
					"name":"财经美女抱",
					"jieshan":"欲练此功，必先自宫",
					"zan_guanzhu":"本期回答积分：1022",
					"imageURl":"img/-camera.jpg"
				}
			]
		}
	]
});
